"""empty message

Revision ID: 0791be4065b7
Revises: 921a2a3d4dd7
Create Date: 2016-04-06 00:12:03.241874

"""

# revision identifiers, used by Alembic.
revision = '0791be4065b7'
down_revision = '921a2a3d4dd7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('ams_role', sa.String(length=20), nullable=True))
    op.add_column('user', sa.Column('crm_role', sa.String(length=20), nullable=True))
    op.add_column('user', sa.Column('hrm_role', sa.String(length=20), nullable=True))
    op.add_column('user', sa.Column('mms_role', sa.String(length=20), nullable=True))
    op.add_column('user', sa.Column('oms_role', sa.String(length=20), nullable=True))
    op.drop_column('user', 'group_roles')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('group_roles', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('user', 'oms_role')
    op.drop_column('user', 'mms_role')
    op.drop_column('user', 'hrm_role')
    op.drop_column('user', 'crm_role')
    op.drop_column('user', 'ams_role')
    ### end Alembic commands ###
