"""empty message

Revision ID: 19647e8c927c
Revises: bae4378d4fe7
Create Date: 2016-04-03 14:04:33.080796

"""

# revision identifiers, used by Alembic.
revision = '19647e8c927c'
down_revision = 'bae4378d4fe7'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('datetime', sa.DateTime(), nullable=True))
    op.drop_column('messages', 'date')
    op.drop_column('messages', 'time')
    op.drop_column('results', 'time')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('time', postgresql.TIME(), autoincrement=False, nullable=True))
    op.add_column('messages', sa.Column('time', postgresql.TIME(), autoincrement=False, nullable=True))
    op.add_column('messages', sa.Column('date', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('messages', 'datetime')
    ### end Alembic commands ###
