"""empty message

Revision ID: 2b356211e42c
Revises: 5315dea79c8d
Create Date: 2016-04-15 23:45:54.506946

"""

# revision identifiers, used by Alembic.
revision = '2b356211e42c'
down_revision = '5315dea79c8d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_permissions', 'id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_permissions', sa.Column('id', sa.INTEGER(), nullable=False))
    ### end Alembic commands ###
