"""empty message

Revision ID: 3a2162fd58de
Revises: 633c71628a85
Create Date: 2016-04-03 11:25:44.460472

"""

# revision identifiers, used by Alembic.
revision = '3a2162fd58de'
down_revision = '633c71628a85'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_last', sa.String(length=80), nullable=False),
    sa.Column('name_first', sa.String(length=80), nullable=False),
    sa.Column('name_prefix', sa.String(length=80), nullable=True),
    sa.Column('name_suffix', sa.String(length=80), nullable=True),
    sa.Column('name_middle', sa.String(length=80), nullable=True),
    sa.Column('email1', sa.String(length=120), nullable=True),
    sa.Column('email2', sa.String(length=120), nullable=True),
    sa.Column('phone1', sa.String(length=20), nullable=True),
    sa.Column('phone2', sa.String(length=20), nullable=True),
    sa.Column('phone3', sa.String(length=20), nullable=True),
    sa.Column('phone4', sa.String(length=20), nullable=True),
    sa.Column('phone5', sa.String(length=20), nullable=True),
    sa.Column('pii_dob', sa.String(length=10), nullable=True),
    sa.Column('pii_other', sa.String(length=500), nullable=True),
    sa.Column('phi', sa.String(length=500), nullable=True),
    sa.Column('pfi', sa.String(length=500), nullable=True),
    sa.Column('address_street', sa.String(length=50), nullable=True),
    sa.Column('address_suite', sa.String(length=20), nullable=True),
    sa.Column('address_state', sa.String(length=2), nullable=True),
    sa.Column('address_county', sa.String(length=20), nullable=True),
    sa.Column('address_zip', sa.String(length=5), nullable=True),
    sa.Column('address_zip_extension', sa.String(length=4), nullable=True),
    sa.Column('billing_method', sa.String(length=50), nullable=True),
    sa.Column('billing_frequency', sa.String(length=50), nullable=True),
    sa.Column('billing_relation_name', sa.String(length=50), nullable=True),
    sa.Column('billing_email', sa.String(length=50), nullable=True),
    sa.Column('billing_address_street', sa.String(length=50), nullable=True),
    sa.Column('billing_address_suite', sa.String(length=20), nullable=True),
    sa.Column('billing_address_state', sa.String(length=2), nullable=True),
    sa.Column('billing_address_county', sa.String(length=20), nullable=True),
    sa.Column('billing_address_zip', sa.String(length=5), nullable=True),
    sa.Column('billing_address_zip_extension', sa.String(length=4), nullable=True),
    sa.Column('billing_notes', sa.String(length=50), nullable=True),
    sa.Column('relation_1_name', sa.String(length=100), nullable=True),
    sa.Column('relation_1_role', sa.String(length=100), nullable=True),
    sa.Column('relation_2_name', sa.String(length=100), nullable=True),
    sa.Column('relation_2_role', sa.String(length=100), nullable=True),
    sa.Column('relation_3_name', sa.String(length=100), nullable=True),
    sa.Column('relation_3_role', sa.String(length=100), nullable=True),
    sa.Column('relation_4_name', sa.String(length=100), nullable=True),
    sa.Column('relation_4_role', sa.String(length=100), nullable=True),
    sa.Column('relation_5_name', sa.String(length=100), nullable=True),
    sa.Column('relation_5_role', sa.String(length=100), nullable=True),
    sa.Column('customer_type', sa.String(length=100), nullable=True),
    sa.Column('customer_type_id1', sa.String(length=100), nullable=True),
    sa.Column('customer_type_id2', sa.String(length=100), nullable=True),
    sa.Column('customer_type_id3', sa.String(length=100), nullable=True),
    sa.Column('service_1_id', sa.String(length=100), nullable=True),
    sa.Column('service_1_day', sa.String(length=100), nullable=True),
    sa.Column('service_1_hours', sa.String(length=100), nullable=True),
    sa.Column('service_1_type', sa.String(length=100), nullable=True),
    sa.Column('service_1_rate', sa.String(length=10), nullable=True),
    sa.Column('service_2_id', sa.String(length=100), nullable=True),
    sa.Column('service_2_day', sa.String(length=100), nullable=True),
    sa.Column('service_2_hours', sa.String(length=100), nullable=True),
    sa.Column('service_2_type', sa.String(length=100), nullable=True),
    sa.Column('service_2_rate', sa.String(length=10), nullable=True),
    sa.Column('service_3_id', sa.String(length=100), nullable=True),
    sa.Column('service_3_day', sa.String(length=100), nullable=True),
    sa.Column('service_3_hours', sa.String(length=100), nullable=True),
    sa.Column('service_3_type', sa.String(length=100), nullable=True),
    sa.Column('service_3_rate', sa.String(length=10), nullable=True),
    sa.Column('service_4_id', sa.String(length=100), nullable=True),
    sa.Column('service_4_day', sa.String(length=100), nullable=True),
    sa.Column('service_4_hours', sa.String(length=100), nullable=True),
    sa.Column('service_4_type', sa.String(length=100), nullable=True),
    sa.Column('service_4_rate', sa.String(length=10), nullable=True),
    sa.Column('service_5_id', sa.String(length=100), nullable=True),
    sa.Column('service_5_day', sa.String(length=100), nullable=True),
    sa.Column('service_5_hours', sa.String(length=100), nullable=True),
    sa.Column('service_5_type', sa.String(length=100), nullable=True),
    sa.Column('service_5_rate', sa.String(length=10), nullable=True),
    sa.Column('service_6_id', sa.String(length=100), nullable=True),
    sa.Column('service_6_day', sa.String(length=100), nullable=True),
    sa.Column('service_6_hours', sa.String(length=100), nullable=True),
    sa.Column('service_6_type', sa.String(length=100), nullable=True),
    sa.Column('service_6_rate', sa.String(length=10), nullable=True),
    sa.Column('notes_case', sa.String(length=100), nullable=True),
    sa.Column('notes_other', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin_roles',
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('permission', sa.String(length=80), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=True),
    sa.Column('write', sa.Boolean(), nullable=True),
    sa.Column('update', sa.Boolean(), nullable=True),
    sa.Column('delete', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('role')
    )
    op.create_table('personnel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_last', sa.String(length=80), nullable=False),
    sa.Column('name_first', sa.String(length=80), nullable=False),
    sa.Column('name_prefix', sa.String(length=80), nullable=True),
    sa.Column('name_suffix', sa.String(length=80), nullable=True),
    sa.Column('name_middle', sa.String(length=80), nullable=True),
    sa.Column('email1', sa.String(length=120), nullable=True),
    sa.Column('email2', sa.String(length=120), nullable=True),
    sa.Column('phone1', sa.String(length=20), nullable=True),
    sa.Column('phone2', sa.String(length=20), nullable=True),
    sa.Column('phone3', sa.String(length=20), nullable=True),
    sa.Column('phone4', sa.String(length=20), nullable=True),
    sa.Column('phone5', sa.String(length=20), nullable=True),
    sa.Column('pii_dob', sa.String(length=10), nullable=True),
    sa.Column('pii_other', sa.String(length=500), nullable=True),
    sa.Column('phi', sa.String(length=500), nullable=True),
    sa.Column('pfi', sa.String(length=500), nullable=True),
    sa.Column('address_street', sa.String(length=50), nullable=True),
    sa.Column('address_suite', sa.String(length=20), nullable=True),
    sa.Column('address_state', sa.String(length=2), nullable=True),
    sa.Column('address_county', sa.String(length=20), nullable=True),
    sa.Column('address_zip', sa.String(length=5), nullable=True),
    sa.Column('address_zip_extension', sa.String(length=4), nullable=True),
    sa.Column('relation_1_name', sa.String(length=100), nullable=True),
    sa.Column('relation_1_notes', sa.String(length=100), nullable=True),
    sa.Column('relation_2_name', sa.String(length=100), nullable=True),
    sa.Column('relation_2_notes', sa.String(length=100), nullable=True),
    sa.Column('notes_other', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_roles',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('permission', sa.String(length=80), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=True),
    sa.Column('write', sa.Boolean(), nullable=True),
    sa.Column('update', sa.Boolean(), nullable=True),
    sa.Column('delete', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_last', sa.String(length=80), nullable=False),
    sa.Column('name_first', sa.String(length=80), nullable=False),
    sa.Column('name_prefix', sa.String(length=80), nullable=True),
    sa.Column('name_suffix', sa.String(length=80), nullable=True),
    sa.Column('name_middle', sa.String(length=80), nullable=True),
    sa.Column('email1', sa.String(length=120), nullable=True),
    sa.Column('email2', sa.String(length=120), nullable=True),
    sa.Column('phone1', sa.String(length=20), nullable=True),
    sa.Column('phone2', sa.String(length=20), nullable=True),
    sa.Column('phone3', sa.String(length=20), nullable=True),
    sa.Column('phone4', sa.String(length=20), nullable=True),
    sa.Column('phone5', sa.String(length=20), nullable=True),
    sa.Column('pii_dob', sa.String(length=10), nullable=True),
    sa.Column('pii_other', sa.String(length=500), nullable=True),
    sa.Column('phi', sa.String(length=500), nullable=True),
    sa.Column('pfi', sa.String(length=500), nullable=True),
    sa.Column('address_street', sa.String(length=50), nullable=True),
    sa.Column('address_suite', sa.String(length=20), nullable=True),
    sa.Column('address_state', sa.String(length=2), nullable=True),
    sa.Column('address_county', sa.String(length=20), nullable=True),
    sa.Column('address_zip', sa.String(length=5), nullable=True),
    sa.Column('address_zip_extension', sa.String(length=4), nullable=True),
    sa.Column('relation_1_name', sa.String(length=100), nullable=True),
    sa.Column('relation_1_notes', sa.String(length=100), nullable=True),
    sa.Column('relation_2_name', sa.String(length=100), nullable=True),
    sa.Column('relation_2_notes', sa.String(length=100), nullable=True),
    sa.Column('notes_other', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('abbreviation', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('admin_role', sa.String(length=20), nullable=True))
    op.add_column('user', sa.Column('group_roles', sa.String(length=500), nullable=True))
    op.drop_column('user', 'groups')
    op.drop_column('user', 'permissions')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('permissions', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('groups', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('user', 'group_roles')
    op.drop_column('user', 'admin_role')
    op.drop_table('agencies')
    op.drop_table('contacts')
    op.drop_table('group_roles')
    op.drop_table('personnel')
    op.drop_table('admin_roles')
    op.drop_table('customers')
    ### end Alembic commands ###
