"""empty message

Revision ID: 5315dea79c8d
Revises: 0791be4065b7
Create Date: 2016-04-15 21:37:27.618285

"""

# revision identifiers, used by Alembic.
revision = '5315dea79c8d'
down_revision = '0791be4065b7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mms_config',
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=200), nullable=False),
    sa.Column('permission_level', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('ams_config',
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=200), nullable=False),
    sa.Column('permission_level', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('oms_config',
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=200), nullable=False),
    sa.Column('permission_level', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('crm_config',
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=200), nullable=False),
    sa.Column('permission_level', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('hrm_config',
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=200), nullable=False),
    sa.Column('permission_level', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.add_column('app_config', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('app_config', sa.Column('updated_on', sa.DateTime(), nullable=True))
    op.add_column('app_contacts', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('app_contacts', sa.Column('updated_on', sa.DateTime(), nullable=True))
    op.add_column('app_messages', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('app_messages', sa.Column('updated_on', sa.DateTime(), nullable=True))
    op.add_column('app_module-registry', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('app_module-registry', sa.Column('updated_on', sa.DateTime(), nullable=True))
    op.add_column('app_notifications', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('app_notifications', sa.Column('updated_on', sa.DateTime(), nullable=True))
    op.add_column('app_permissions', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('app_permissions', sa.Column('updated_on', sa.DateTime(), nullable=True))
    op.add_column('app_roles', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('app_roles', sa.Column('updated_on', sa.DateTime(), nullable=True))
    op.add_column('app_users', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('app_users', sa.Column('updated_on', sa.DateTime(), nullable=True))
    op.add_column('crm_agencies', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('crm_agencies', sa.Column('updated_on', sa.DateTime(), nullable=True))
    op.add_column('crm_customers', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('crm_customers', sa.Column('updated_on', sa.DateTime(), nullable=True))
    op.add_column('hrm_personnel', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('hrm_personnel', sa.Column('updated_on', sa.DateTime(), nullable=True))
    op.add_column('mms_word-analysis-results', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('mms_word-analysis-results', sa.Column('updated_on', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mms_word-analysis-results', 'updated_on')
    op.drop_column('mms_word-analysis-results', 'created_on')
    op.drop_column('hrm_personnel', 'updated_on')
    op.drop_column('hrm_personnel', 'created_on')
    op.drop_column('crm_customers', 'updated_on')
    op.drop_column('crm_customers', 'created_on')
    op.drop_column('crm_agencies', 'updated_on')
    op.drop_column('crm_agencies', 'created_on')
    op.drop_column('app_users', 'updated_on')
    op.drop_column('app_users', 'created_on')
    op.drop_column('app_roles', 'updated_on')
    op.drop_column('app_roles', 'created_on')
    op.drop_column('app_permissions', 'updated_on')
    op.drop_column('app_permissions', 'created_on')
    op.drop_column('app_notifications', 'updated_on')
    op.drop_column('app_notifications', 'created_on')
    op.drop_column('app_module-registry', 'updated_on')
    op.drop_column('app_module-registry', 'created_on')
    op.drop_column('app_messages', 'updated_on')
    op.drop_column('app_messages', 'created_on')
    op.drop_column('app_contacts', 'updated_on')
    op.drop_column('app_contacts', 'created_on')
    op.drop_column('app_config', 'updated_on')
    op.drop_column('app_config', 'created_on')
    op.drop_table('hrm_config')
    op.drop_table('crm_config')
    op.drop_table('oms_config')
    op.drop_table('ams_config')
    op.drop_table('mms_config')
    ### end Alembic commands ###
