"""empty message

Revision ID: 59f3cb2791a6
Revises: 2b356211e42c
Create Date: 2016-04-22 00:49:19.031960

"""

# revision identifiers, used by Alembic.
revision = '59f3cb2791a6'
down_revision = '2b356211e42c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crm_customers', sa.Column('address_city', sa.String(length=30), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crm_customers', 'address_city')
    ### end Alembic commands ###
