"""empty message

Revision ID: 633c71628a85
Revises: 6ef86889eac2
Create Date: 2016-03-28 23:36:48.733473

"""

# revision identifiers, used by Alembic.
revision = '633c71628a85'
down_revision = '6ef86889eac2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    ### end Alembic commands ###
