"""empty message

Revision ID: 6ef86889eac2
Revises: b6b8280dfd06
Create Date: 2016-03-28 21:29:51.892424

"""

# revision identifiers, used by Alembic.
revision = '6ef86889eac2'
down_revision = 'b6b8280dfd06'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    ### end Alembic commands ###
