"""empty message

Revision ID: 7c7dddf84756
Revises: c8bc82edea1d
Create Date: 2016-04-03 13:14:47.565420

"""

# revision identifiers, used by Alembic.
revision = '7c7dddf84756'
down_revision = 'c8bc82edea1d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('abbreviation', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('results', sa.Column('date', sa.Date(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('results', 'date')
    op.drop_table('modules')
    ### end Alembic commands ###
