"""empty message

Revision ID: 921a2a3d4dd7
Revises: 19647e8c927c
Create Date: 2016-04-03 14:15:40.128159

"""

# revision identifiers, used by Alembic.
revision = '921a2a3d4dd7'
down_revision = '19647e8c927c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=30), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('subcategory', sa.String(length=20), nullable=True),
    sa.Column('body', sa.String(length=1000), nullable=True),
    sa.Column('author', sa.String(length=30), nullable=True),
    sa.Column('delivery_methods', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('app_notifications')
    ### end Alembic commands ###
