"""empty message

Revision ID: b6b8280dfd06
Revises: b4a25fc11bfd
Create Date: 2016-03-28 01:57:04.956553

"""

# revision identifiers, used by Alembic.
revision = 'b6b8280dfd06'
down_revision = 'b4a25fc11bfd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('messages_user_id_fkey', 'messages', type_='foreignkey')
    op.drop_column('messages', 'user_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('messages_user_id_fkey', 'messages', 'user', ['user_id'], ['id'])
    ### end Alembic commands ###
