"""empty message

Revision ID: bae4378d4fe7
Revises: 7c7dddf84756
Create Date: 2016-04-03 13:54:54.835748

"""

# revision identifiers, used by Alembic.
revision = 'bae4378d4fe7'
down_revision = '7c7dddf84756'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'agencies', ['abbreviation'])
    op.create_unique_constraint(None, 'agencies', ['name'])
    op.add_column('messages', sa.Column('date', sa.Date(), nullable=True))
    op.add_column('messages', sa.Column('time', sa.Time(), nullable=True))
    op.create_unique_constraint(None, 'modules', ['abbreviation'])
    op.create_unique_constraint(None, 'modules', ['name'])
    op.add_column('results', sa.Column('time', sa.Time(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('results', 'time')
    op.drop_constraint(None, 'modules', type_='unique')
    op.drop_constraint(None, 'modules', type_='unique')
    op.drop_column('messages', 'time')
    op.drop_column('messages', 'date')
    op.drop_constraint(None, 'agencies', type_='unique')
    op.drop_constraint(None, 'agencies', type_='unique')
    ### end Alembic commands ###
