"""empty message

Revision ID: bd578ecd2f57
Revises: b8e1384272d4
Create Date: 2016-04-03 11:57:44.572282

"""

# revision identifiers, used by Alembic.
revision = 'bd578ecd2f57'
down_revision = 'b8e1384272d4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modules', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('modules', sa.Column('description', sa.String(length=200), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('modules', 'description')
    op.drop_column('modules', 'active')
    ### end Alembic commands ###
