"""empty message

Revision ID: c0587e8beb97
Revises: 561fbe10f708
Create Date: 2016-03-28 01:29:41.593158

"""

# revision identifiers, used by Alembic.
revision = 'c0587e8beb97'
down_revision = '561fbe10f708'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('groups', sa.String(length=500), nullable=True))
    op.add_column('user', sa.Column('permissions', sa.String(length=500), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'permissions')
    op.drop_column('user', 'groups')
    ### end Alembic commands ###
