"""empty message

Revision ID: c8bc82edea1d
Revises: bd578ecd2f57
Create Date: 2016-04-03 12:53:52.092390

"""

# revision identifiers, used by Alembic.
revision = 'c8bc82edea1d'
down_revision = 'bd578ecd2f57'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('module', sa.String(length=3), nullable=True),
    sa.Column('permission', sa.String(length=80), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('write', sa.Boolean(), nullable=False),
    sa.Column('update', sa.Boolean(), nullable=False),
    sa.Column('delete', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('module_abbreviation', sa.String(length=3), nullable=False),
    sa.PrimaryKeyConstraint('role', 'module_abbreviation')
    )
    op.drop_table('admin_roles')
    op.drop_table('group_roles')
    op.alter_column('modules', 'abbreviation',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('modules', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('modules', 'description',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.drop_column('modules', 'id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modules', sa.Column('id', sa.INTEGER(), nullable=False))
    op.alter_column('modules', 'description',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('modules', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('modules', 'abbreviation',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.create_table('group_roles',
    sa.Column('permission', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('read', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('write', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('update', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('delete', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(length=20), autoincrement=False, nullable=False)
    )
    op.create_table('admin_roles',
    sa.Column('role', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('permission', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('read', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('write', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('update', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('delete', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('role', name='admin_roles_pkey')
    )
    op.drop_table('roles')
    op.drop_table('permissions')
    ### end Alembic commands ###
