"""empty message

Revision ID: ce80d3445719
Revises: 59f3cb2791a6
Create Date: 2016-04-22 00:52:48.788004

"""

# revision identifiers, used by Alembic.
revision = 'ce80d3445719'
down_revision = '59f3cb2791a6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hrm_personnel', sa.Column('address_city', sa.String(length=30), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hrm_personnel', 'address_city')
    ### end Alembic commands ###
