"""empty message

Revision ID: eb9f01779934
Revises: ce80d3445719
Create Date: 2016-04-30 02:03:05.566422

"""

# revision identifiers, used by Alembic.
revision = 'eb9f01779934'
down_revision = 'ce80d3445719'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('modules_abbreviation_key', 'app_module-registry', type_='unique')
    op.drop_constraint('modules_name_key', 'app_module-registry', type_='unique')
    op.drop_constraint('app_notifications_title_key', 'app_notifications', type_='unique')
    op.drop_constraint('user_email_key', 'app_users', type_='unique')
    op.drop_constraint('user_username_key', 'app_users', type_='unique')
    op.drop_constraint('agencies_abbreviation_key', 'crm_agencies', type_='unique')
    op.drop_constraint('agencies_name_key', 'crm_agencies', type_='unique')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('agencies_name_key', 'crm_agencies', ['name'])
    op.create_unique_constraint('agencies_abbreviation_key', 'crm_agencies', ['abbreviation'])
    op.create_unique_constraint('user_username_key', 'app_users', ['username'])
    op.create_unique_constraint('user_email_key', 'app_users', ['email'])
    op.create_unique_constraint('app_notifications_title_key', 'app_notifications', ['title'])
    op.create_unique_constraint('modules_name_key', 'app_module-registry', ['name'])
    op.create_unique_constraint('modules_abbreviation_key', 'app_module-registry', ['abbreviation'])
    ### end Alembic commands ###
